[telepathy-mission-control]
source = "git"
git = "https://gitlab.freedesktop.org/telepathy/telepathy-mission-control.git"
include_regex = 'telepathy-mission-control-\d+\.\d*[02468]\.\d*'
prefix = "telepathy-mission-control-"
