[xf86-input-elographics]
source = "gitlab"
gitlab = "xorg/driver/xf86-input-elographics"
host = "gitlab.freedesktop.org"
use_max_tag = true

include_regex = ".*xf86-input-elographics-.*"
prefix = "xf86-input-elographics-"
