[docbook-dsssl]
#source = "github"
#github = "docbook/dsssl"
#use_max_tag = true
#ignore = "SVNSNAPSHOT"

source = "regex"
regex = "version (\\d+.\\d+)"
url = "https://github.com/docbook/dsssl/releases"
