[libnbd]
source = "git"
git = "https://gitlab.com/nbdkit/libnbd"
# only even minor versions are considered stable, because semver doesn't exist
include_regex = "^(v|)([\\d.]+).([\\d]*)[02468]{1}.([\\d.]+)$"
prefix = "v"
