[hyphen-de]
#source = "git"
#git = "https://anongit.freedesktop.org/git/libreoffice/dictionaries.git"
#use_max_tag = true

source = "regex"
regex = "title='([\\d-]+)"
url = "https://cgit.freedesktop.org/libreoffice/dictionaries/log/de"
from_pattern = '(\d+)-(\d+)-(\d+)'
to_pattern = '\1\2\3'
