[xf86-video-voodoo]
source = "gitlab"
gitlab = "xorg/driver/xf86-video-voodoo"
host = "gitlab.freedesktop.org"
use_max_tag = true

include_regex = ".*xf86-video-voodoo-.*"
prefix = "xf86-video-voodoo-"
