[xf86-video-intel]
source = "gitlab"
gitlab = "xorg/driver/xf86-video-intel"
host = "gitlab.freedesktop.org"
use_max_tag = true

#include_regex = ".*xf86-video-intel-.*"
#prefix = "xf86-video-intel-"
