[xf86-video-nouveau]
source = "gitlab"
gitlab = "xorg/driver/xf86-video-nouveau"
host = "gitlab.freedesktop.org"
use_max_tag = true

include_regex = ".*xf86-video-nouveau-.*"
prefix = "xf86-video-nouveau-"
