[c-ares]
source = "git"
git = "https://github.com/c-ares/c-ares"
include_regex = '(cares)-([\d_].*)'
exclude_regex = ".*(dev|rc|RC|alpha|beta|bp).*"
from_pattern = 'cares-(\d+)_(\d+)_(\d+)'
to_pattern = '\1.\2.\3'
