[crimson-pro-font]
# source = "github"
# github = "Fonthausen/CrimsonPro"
# use_max_tag = true

# This is a crude hack because regex doesn't support combining results with
# padding very well so we're fudging with our knowledge that Google Fonts has
# a rule against bumping major versions at all, and hoping that if they do
# change the minor version it will at least turn up as a new version even if
# the suggested new version string is incorrectly padded.
source = "regex"
url = "https://raw.githubusercontent.com/Fonthausen/CrimsonPro/master/sources/CrimsonPro.glyphs"
regex = "versionMinor = (\\d+);"
from_pattern = "(\\d+)"
to_pattern = "1.00\\1"
