[xorg-xconsole]
source = "gitlab"
gitlab = "xorg/app/xconsole"
host = "gitlab.freedesktop.org"
use_max_tag = true

include_regex = ".*xconsole-.*"
prefix = "xconsole-"
#source = "regex"
#regex = "xconsole-([\\d.]+)\\."
#url = "https://gitlab.freedesktop.org/xorg/xserver/-/tags"
