[xcb-util-renderutil]
source = "gitlab"
gitlab = "xorg/lib/libxcb-render-util"
host = "gitlab.freedesktop.org"

include_regex = ".*xcb-util-renderutil-.*"
use_max_tag = true
prefix = "xcb-util-renderutil-"
