# Disabled as chasing every commit is tedious
[tt-rss]
source = "git"
git = "https://gitlab.tt-rss.org/tt-rss/tt-rss.git"
use_commit = true

# Custom attributes used by https://gitlab.com/yan12125/aur/
__custom_attributes__.pkgbuild_field = "$_commit"
