[hunspell-hu]
source = "regex"
url = "https://cgit.freedesktop.org/libreoffice/dictionaries/plain/hu_HU/README_hu_HU.txt"
regex = "Hungarian Hunspell dictionaries version (.*) with morphological data"
