[nawk]
# source = "github"
# github = "onetrueawk/awk"
# use_max_tag = true

# Upstream stopped publishing tags and declared master to be stable, but they
# occasionally bump the embeded version string.
source = "regex"
url = "https://raw.githubusercontent.com/onetrueawk/awk/master/main.c"
regex = '\*version = "version (\d+)";'
