[xf86-video-sisusb]
source = "gitlab"
gitlab = "xorg/driver/xf86-video-sisusb"
host = "gitlab.freedesktop.org"
use_max_tag = true

include_regex = ".*xf86-video-sisusb-.*"
prefix = "xf86-video-sisusb-"
