[distribution-gpg-keys]
source = "git"
git = "https://github.com/rpm-software-management/distribution-gpg-keys.git"
from_pattern = 'distribution-gpg-keys-(\d+).(\d+)-\d+'
to_pattern = '\1.\2'
# distribution-gpg-keys-1.104-1
