[xf86-video-vmware]
source = "gitlab"
gitlab = "xorg/driver/xf86-video-vmware"
host = "gitlab.freedesktop.org"
use_max_tag = true

include_regex = ".*xf86-video-vmware-.*"
prefix = "xf86-video-vmware-"
