[bogofilter]
source = "gitlab"
gitlab = "bogofilter/bogofilter"
use_max_tag = true
prefix = "bogofilter-"
ignored = "unlabeled-1.1.2 svn-to-git-conversion stable-0_13_6_2-fixes mime-final-Jan-12-2003 initial datastore_tc"
