[poppler-data]
#source = "gitlab"
#gitlab = "poppler/poppler-data"
#host = "gitlab.freedesktop.org"
#branch = "master"
#include_prereleases = true
#use_max_tag = true
#use_latest_tag = true
#use_latest_release = true
##prefix = "poppler-"

#source = "git"
#git = "https://gitlab.freedesktop.org/poppler/poppler-data.git"
#ignored = "start"
#use_max_tag = true

source = "regex"
regex = "poppler-data-([\\d.]+)\\."
url = "https://poppler.freedesktop.org/"
