[darktable]
source = "github"
github = "darktable-org/darktable"
prefix = "release-"
use_latest_release = true
# ignore old tag schemes, rcs, etc by only including release tag scheme
include_regex = "release-\\d+\\.\\d+\\.\\d+"
# Y=odd Z=0 are dev series, not stable
exclude_regex = "release-\\d+\\.\\d*[13579]\\.0"
