[foomatic-db-engine]
source = "github"
github = "OpenPrinting/foomatic-db-engine-4"
# gives date+clock: 20200131.095854 - no tags
#use_max_tag = true

#source = "git"
#git = "https://github.com/OpenPrinting/foomatic-db-engine-4.git"
#use_commit = "true"
