[docbook-sgml31]
#source = "github"
#github = "docbook/dsssl"
#use_max_tag = true
#ignore = "SVNSNAPSHOT"

source = "regex"
regex = "\\d+.\\d+"
include_regex = "3.1*"
#exclude_regex = "1999"
url = "https://docbook.org/sgml/"
