[python-cfn-lint]
source = "pypi"
pypi = "cfn-lint"
# python-moto is not compatible with cfn-lint 1.x yet
# That should likely be fixed with https://github.com/getmoto/moto/pull/7784
include_regex = "^0\\..*"
