[docbook-mathml]
#source = "github"
#github = "docbook/dsssl"
#use_max_tag = true
#ignore = "SVNSNAPSHOT"

source = "regex"
regex = "The DocBook MathML Document Type, Working Draft (\\d.+)[,]"
url = "https://docbook.org/specs/"
