# BIND versions are typically in the form of X.Y.Z where "Y"
# is an even number for stable releases or an odd number for
# development releases.
# https://kb.isc.org/docs/aa-01540

[bind]
source = "git"
git = "https://gitlab.isc.org/isc-projects/bind9.git"
prefix = "v"
exclude_regex = "v[0-9]+\\.[0-9]?[13579]\\.[0-9]+"
