[python-botocore]
source = "pypi"
pypi = "botocore"

# Custom attributes used by https://gitlab.com/yan12125/aur/
__custom_attributes__.group = "aws"
__custom_attributes__.extras = ["crt"]
__custom_attributes__.non_nvchecker = true
