[ttf-roboto-mono]
source = "htmlparser"
url = "https://raw.githubusercontent.com/googlefonts/RobotoMono/main/sources/RobotoMono-Regular.ufo/fontinfo.plist"
xpath = "concat(//plist/dict/key[.='versionMajor']/following-sibling::integer[1],'.',//plist/dict/key[.='versionMinor']/following-sibling::integer[1])"
