[apache]
#source = "git"
#git = "https://github.com/apache/httpd.git"
#exclude_regex = ".*(alpha|beta).*"

source = "regex"
url = "https://downloads.apache.org/httpd/"
regex = "href=\"httpd-(.*)\\.tar.gz.*\""
