[runc]
source = "github"
github = "opencontainers/runc"
use_max_tag = true
prefix = "v"
from_pattern = "v(\\d+)\\.(\\d+)\\.(\\d+)\\-rc(\\d+)"
to_pattern = "\\1.\\2.\\3rc\\4"
exclude_regex = "v.*(rc|alpha|beta).*"
